2024-12-25 18:23:15,701 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "E:\PyCharm_Projects\module_12_4\test_12_4.py", line 22, in test_run
    runner_run = rt_with_exceptions.Runner('Will', -5)
  File "E:\PyCharm_Projects\module_12_4\rt_with_exceptions.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
2024-12-25 18:23:15,702 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "E:\PyCharm_Projects\module_12_4\test_12_4.py", line 13, in test_walk
    runner_walk = rt_with_exceptions.Runner(5, 10)
  File "E:\PyCharm_Projects\module_12_4\rt_with_exceptions.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
